swagger: "2.0"
info:
  description: "Simple API to manage customers"
  version: "1.0.0"
  title: "Customers API"
host: "localhost:3000"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
tags:
- name: "customer"
  description: "operations on customers"
paths:
  /customers:
    get:
      tags:
      - "customer"
      summary: "Get a list of customers"
      description: ""
      responses:
        "200":
          description: "Everything went well"
          schema:
            type: 'object'
            properties:
              data:
                type: 'array'
                items: 
                  $ref: '#/definitions/CustomerSimplified'
    post:
      tags:
      - "customer"
      summary: "Add a new customer"
      description: ""
      parameters:
      - in: "body"
        name: "customer"
        description: "Customer object that needs to be added in DB"
        required: true
        schema:
          allOf:
           - $ref: "#/definitions/CustomerEditableAttributes"
           - type: 'object'
             required:
              - "email"
      responses:
        "201":
          description: "Created"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Customer"
        "400":
          description: "Invalid input. The customer object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
          
  /customers/{customerId}:
    get:
      tags:
      - "customer"
      summary: "Find a customer by ID"
      description: "Returns a single customer"
      parameters:
      - name: "customerId"
        in: "path"
        description: "ID of customer to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: 'object'
            properties:
              data:
                type: "object"
                $ref: "#/definitions/Customer"
        "404":
          description: "customer not found"
    put:
      tags:
      - "customer"
      summary: "Update an existing customer"
      description: ""
      parameters:
      - name: "customerId"
        in: "path"
        description: "ID of customer to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "customer"
        description: "customer object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/CustomerEditableAttributes"
      responses:
        "200":
          description: "Updated"
          schema:
            type: "object"
            properties:
              data:
                $ref: "#/definitions/Customer"
        "404":
          description: "customer not found"
        "400":
          description: "Invalid input. The customer object provided is not valid"
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: "string"
    delete:
      tags:
      - "customer"
      summary: "Deletes a customer"
      description: ""
      parameters:
      - name: "customerId"
        in: "path"
        description: "customer id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "404":
          description: "customer not found"
        "200":
          description: "OK"
definitions:
  CustomerEditableAttributes:
    type: "object"
    properties:
      first_name:
        type: "string"
        example: "John"
      last_name:
        type: "string"
        example: "Doe"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  CustomerSimplified:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "John"
      email: 
        type: "string"
        example: "john.doe@gmail.com"
      active: 
        type: "boolean"
      
  Customer:
    allOf: 
      - type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
      - $ref: '#/definitions/CustomerEditableAttributes'
      